name: Sample SSH server workflow

on:
  workflow_dispatch:
    inputs:
      sshPublicKey:
        description: 'SSH public key'
        required: true
      exitCode:
        description: 'When set to non-zero, a step will fail causing the SSH server to be started'
        required: true
        default: "0"
      os:
        description: 'OS'
        required: true
        default: 'macos-latest'
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
      timeout:
        description: 'How long to run (minutes)'
        required: false
        type: number
        default: "10"

jobs:
  sample:
    name: Sample
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Exit code
      run: |
        exit "${{ github.event.inputs.exitCode }}"

    - name: Start SSH server on failure
      if: ${{ failure() }}
      timeout-minutes: ${{ fromJSON(inputs.timeout) }}
      uses: ./
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ github.event.inputs.sshPublicKey }}"
